### ISSUE TITLE
--no_download_files flag is not working

### ISSUE THREAD

**Issue by armaseg** [glimmerphoenix/WikiDAT#17]
I already downloaded a dump and when I try to use the *--no_download_files flag* it says that the files are not there. This is the output:

```
$ python main.py --no_download_files
()
*** WIKIPEDIA DATA ANALYSIS TOOLKIT ***
()
----------------------------------------------------------
Executing ETL:RevHistory on lang: scowiki date: 20151102
ETL lines = 1 page_fan = 1 rev_fan = 1
('Download files =', False)
Start time is 2015-12-22 15:48:28 CET
----------------------------------------------------------
()
Looking for revision-history dump file(s) in data dir
Directory data/scowiki_dumps/20151102 does not contain any valid dump file.
Program will exit now.
```

**Comment by glimmerphoenix** [comment]
Thanks for fixing the typos!

Please note the `()` between some of the lines in your output. I suspect that you are trying to execute the program using Python 2 (probably v2.7) instead of Python 3. Currently, the whole code has already been migrated to Python 3 (v3.4 or later), so you must use that Python version to run the tool.

I will update the documentation ASAP to reflect these changes, since now that is not very clear. Using `virtualenv` or a Python distribution like *Anaconda* (https://www.continuum.io/downloads) it is very easy to create an isolated environment with Python 3.5 and the required packages to run this tool.

Please, confirm that this is the case to close the bug report.
